hydra:
  output_subdir: null  
  run:
    dir: .

defaults:
  - process: process1
  - model: model1
  - _self_

data:
  raw: ../data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv
  processed: data/processed/processed.csv
  final: data/final/final.csv

churn:
  target: churn


